# Generated by Django 4.1.7 on 2023-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='fake description', max_length=255),
            preserve_default=False,
        ),
    ]
